### ISSUE TITLE
No method matching on 32 bit machine

### ISSUE THREAD

**Issue by daharn** [JuliaSIMD/VectorizationBase.jl#74]
I get the following error when using v0.21.18 on a 32 bit machine.

```julia
LoadError: MethodError: no method matching vload_transpose_quote(::Int32, ::Int32, ::Int32, ::Int32, ::Int32, ::Int32, ::Int32, ::Bool, ::Int32, ::Int32, ::UInt64, ::Bool)
  Closest candidates are:
    vload_transpose_quote(::Int32, ::Int32, ::Int32, ::Int32, ::Int32, ::Int32, ::Int32, ::Bool, ::Int32, ::Int32, ::UInt32, ::Bool) at /home/runner/.julia/packages/VectorizationBase/Q2q04/src/vecunroll/memory.jl:204
```

Running the same code on 64 bit causes no error.

**Comment by chriselrod** [comment]
Hopefully fixed by

**Comment by chriselrod** [comment]
The tests segfault on x86 Windows.
If that's a problem, feel free to file another issue.
I don't have a Windows machine on which to test and debug.
Tests pass on Linux.

**Comment by daharn** [comment]
Unfortunately I still receive the exact same error message with v0.21.19 on both x86 linux and Windows.
I only use github actions to test my package on x86 builds too, this is where this shows up. I don't have any x86 os locally to further test this.

**Comment by chriselrod** [comment]
> Unfortunately I still receive the exact same error message with v0.21.19 on both x86 linux and Windows.
> I only use github actions to test my package on x86 builds too, this is where this shows up. I don't have any x86 os locally to further test this.

Please provide a reproducer.

**Comment by chriselrod** [comment]
> I don't have any x86 os locally to further test this.

If you have an x64 OS locally, you should be able to just install and run an x86 binary.

**Comment by daharn** [comment]
> > Unfortunately I still receive the exact same error message with v0.21.19 on both x86 linux and Windows.
> > I only use github actions to test my package on x86 builds too, this is where this shows up. I don't have any x86 os locally to further test this.
> 
> Please provide a reproducer, or at least a stack trace. The only information I have to go off of here is that the indicated function received a `UInt64` argument when it should have received `UInt32`. But received from what caller, where?

Sorry, for the missing information! I added a stacktrace.
And thanks for the hint regarding 32bit Julia on a 64bit system, I will try this as soon as possible.

**Comment by chriselrod** [comment]
Thanks for the stacktrace. 
Should be fixed by: https://github.com/JuliaSIMD/TriangularSolve.jl/commit/e5d987c44aaa66b8f5c52c91c6ca2ad2e7ffb248

**Comment by daharn** [comment]
Haha, yeah, those hard-coded UInt64 just _might_ be the culprit. ;)

Unsurprisingly, this did the trick. Thanks a lot for the quick fix!
